# Generated by Django 5.2.3 on 2025-06-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_api', '0002_delete_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='availability',
            field=models.JSONField(default=dict),
        ),
    ]
